#%RAML 1.0
title: Customer API
version: v1
description: Is a RESTful API using RAML that contains a single resource, customer.

protocols: [  HTTP, HTTPS ]
baseUri: https://mocksvc.mulesoft.com/mocks/3586a8ad-7919-47a7-8ea4-e1426bcb9305/{environment}/{version} # baseUri: "http://{environment}/{version}"
baseUriParameters:
  environment:
    type: string
    enum: [ "localhost","DEV", "SIT", "UAT", "PREPROD", "PROD" ]
mediaType: [ application/json ]
resourceTypes:
    collection: !include resourceTypes/collection.raml
    item: !include resourceTypes/item.raml

uses:
  Types:  dataTypes/Types.raml
  traits: traits/traits.raml

securitySchemes:
  BasicAuth: !include securitySchemes/BasicAuth.raml
  OAuth2_0: !include securitySchemes/OAuth2_0.raml

securedBy: BasicAuth

/customers:
  description: List of Customers
  post:
    is: [traits.source-trackable,traits.auditable, traits.4xx-errorable,traits.versioned,traits.5xx-errorable,traits.conflict-errorable,traits.cross-originable ]
    description: Create a new <<resourcePathName|!singularize>>
    body:
      application/json:
        example: !include examples/customer/PostCustomer.raml
    responses:
      201:
        description: |
            Succesfully created a new resource
        headers:
            Location:
              description: |
                Location of the newly created resource
              type: string
              required: false
  get:
    is: [ traits.source-trackable,traits.pageable, traits.sortable,traits.versioned ,traits.auditable,traits.4xx-errorable,traits.5xx-errorable]
    description: Get a list of <<resourcePathName>>
    responses:
      200:
        body:
          application/json:
              example: !include examples/customer/GetCustomers.raml
  /{customer_id}:
    get:
      is: [ traits.versioned,traits.content-cacheable,traits.partial,traits.4xx-errorable,traits.5xx-errorable,traits.auditable]
      description: |
        Retrieve the specified <<resourcePathName>>
      responses:
        200:
          description: |
            Succesfully retrieved <<resourcePathName>>
          body:
            application/json:
              example:
                !include examples/customer/GetCustomer.raml
        404:
          description: Resource not found
          body:
            application/json:
              type: !include dataTypes/Error.raml
              example:
                error_code: Not found
                error_detail: The requested resource could not be found but may be available in the future.
    patch:
      is: [ traits.versioned ,traits.4xx-errorable,traits.auditable,traits.conflict-errorable,traits.5xx-errorable]
      description: |
        Update a field of a <<resourcePathName>>
      body:
        application/json:
          example: !include examples/customer/PatchCustomer.raml
      responses:
        204:
          description: Succesfully updated <<resourcePathName>>
        404:
          description: Resource not found
          body:
            application/json:
              type: !include dataTypes/Error.raml
              example:
                        error_code: Not found
                        error_detail: The requested resource could not be found but may be available in the future.
    put:
      is: [ traits.versioned,traits.conflict-errorable,traits.4xx-errorable,traits.5xx-errorable ]
      description: Update an existing <<resourcePathName>>
      body:
        application/json:
          example: !include examples/customer/PutCustomer.raml
      responses:
        204:
          description: |
            Succesfully updated the resource
        404:
          description: Resource not found
          body:
            application/json:
              type: !include dataTypes/Error.raml
              example:
                        error_code: Not found
                        error_detail: The requested resource could not be found but may be available in the future.
        409:
          body:
            application/json:
               example:  
                error_code: Conflict
                error_detail: Request could not be processed because of conflict in the current state of the resource
    delete:
      is: [ traits.versioned ]
      description: |
        Delete resource
      responses:
        204:
          description: |
            Succesfully deleted resource
        404:
          body:
            application/json:
              example: |
               {"message": "<<resourcePathName|!singularize>> not found" }
