#%RAML 1.0

title: Customers API
version: v1
mediaType: application/json
protocols: [ HTTPS ,HTTP]
baseUri: https://mocksvc.mulesoft.com/mocks/346890c4-4a7a-4e37-9d9c-6fbf83567a1a/{version} # baseUri: http://localhost/{version}

uses:
    Types:  dataTypes/Types.raml

securitySchemes:
  BasicAuth: !include security/BasicAuth.raml  
  OAuth2_0: !include security/OAuth2_0.raml

securedBy: BasicAuth
   
resourceTypes:
  collection: !include resourceTypes/collection.raml
  item: !include resourceTypes/item.raml

/customers:
  type:
    collection:
      response-example: !include examples/customer/GetCustomers.raml
      request-example:  !include examples/customer/PostCustomer.raml    

  /{customer_id}:
    type:
      item:
        get-response-example: !include examples/customer/GetCustomer.raml
        patch-request-example: !include examples/customer/PatchCustomer.raml
        put-request-example: !include examples/customer/PutCustomer.raml
    /orders:
      type:
        collection:
          response-example: !include examples/order/GetOrders.raml
          request-example:  !include examples/order/PostOrder.raml 
      /{order_id}:
        type:
          item:
            get-response-example: !include examples/order/GetOrder.raml
            patch-request-example: !include examples/order/PatchOrder.raml
            put-request-example: !include examples/order/PutOrder.raml
    /products:
      type:
        collection:
          response-example: !include examples/product/GetProducts.raml
          request-example:  !include examples/product/PostProduct.raml
      /{product_id}:
        type:
          item:
            get-response-example: !include examples/product/GetProduct.raml
            patch-request-example: !include examples/product/PatchProduct.raml
            put-request-example: !include examples/product/PutProduct.raml        
