#%RAML 1.0 Extension

extends: ../customers-api.raml
usage: Extension of the API to support future resources For example orders and products

uses:
    Types: ../types/Types.raml

resourceTypes:
  collection:       !include ../resourceTypes/collection.raml
  collection-item:  !include ../resourceTypes/item.raml

/Orders:
  type:
    collection:
      request-example: !include ../examples/order/PostOrder.raml
      response-example: !include ../examples//order/GetOrders.raml
  /{id}:
    type:
      collection-item:
        get-response-example: !include ../examples/order/GetOrder.raml
        patch-request-example: !include ../examples/order/PatchOrder.raml
        put-request-example: !include ../examples/order/PutOrder.raml
    /customers:
      type:
        collection-item:
          get-response-example: !include ../examples/customer/GetCustomers.raml
          patch-request-example: |
            {}
          put-request-example: |
            {}
    /products:
      type:
        collection-item:
          get-response-example: !include ../examples/product/GetProducts.raml
          patch-request-example: |
            {}
          put-request-example: |
            {}
/Products:
  type:
    collection:
      request-example: !include ../examples/product/PostProduct.raml
      response-example: !include ../examples/product/GetProducts.raml
  /{id}:
    type:
      collection-item:
        get-response-example: !include ../examples/product/GetProduct.raml
        patch-request-example: !include ../examples/product/PatchProduct.raml
        put-request-example: !include ../examples/product/PutProduct.raml
