#%RAML 1.0 Library

usage:  Traits for the Customer API

traits:
  cacheable: !include cacheable.raml
  pageable: !include pageable.raml
  partial: !include partial.raml
  searchable: !include searchable.raml
  sortable: !include sortable.raml
  versioned: !include versioned.raml
  

  