#%RAML 1.0 NamedExample
value:
-
  id: c42af9c6-b01b-4a91-a88b-c15cdbe1ecad
  order_id: 1
  product_ids: 
  - 
    1
  - 
    2
  - 
    3
  total_cost: "AUD 1000"
-
  id: 6a23dd64-47a3-40c3-a1cc-ec2d09cb871a
  order_id: 2
  product_ids: 
  - 
    4
  - 
    5
  - 
    6
  total_cost: "AUD 2000"