#%RAML 1.0 Library

usage: DataTypes for the Customer API

types: 
  Address: !include Address.raml
  Customer: !include Customer.raml
  NewCustomer: !include NewCustomer.raml
  PatchCustomer: !include PatchCustomer.raml
  

    